--- #YAML:1.0
name:               Finance-InteractiveBrokers-SWIG
version:            0.11
abstract:           InteractiveBrokers API C++ wrapper and connector
author:
    - Jason McManus <infidel AT cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
    Finance::InteractiveBrokers::API:  0
build_requires:
    Alien::InteractiveBrokers:  0
    Finance::InteractiveBrokers::API:  0.02_03
requires:
    Finance::InteractiveBrokers::API:  0.04
    Test::More:           0.88
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
